http {
	server {
		listen 80 15;
		autoindex yes;
		server_name localhost;
		root /var/www/html;
		index index.html;
		location / {
			index inde # test
		}
		error_page 404 /404.html;
		client_max_body_size 1;
	}

}