http {
	keepalive_timeout	10;
	server {
		listen 8080
		autoindex on;
		server_name localhost;
		index index.html;
		root www/html;
		# location / # asfaf afadfadf adfdafad dafdafda dafdafda
		# {
		# 	index inde # test
		# 	methods GET POST;
		# }
		location /cgi {
			index index.php;
		}
		error_page 404 405 406 407 408 /40X.html;
		error_page 500 /500.html
		client_max_body_size 1




















		
	}

}